ADDED THE DARK AND LIGHT MODE FUNCTIONALITY
twitter/opensource-website pull request #123
Opened 2021-08-25 07:11 UTC by Chirag77302

Hey everyone , 
I have added the dark and light mode button functionality which changes the theme of the website to night/dark mode on clicking and reverts it back to the original theme on clicking the light mode , as mentioned in issue (#108) 
Do give out your suggestions for the changes made .

2021-08-25 07:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twitter/opensource-website?pullRequest=123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twitter/opensource-website?pullRequest=123) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twitter/opensource-website?pullRequest=123) it.</sub>

2021-08-25 16:00 UTC, willnorris commented
I'm not actually convinced we even need a dark mode here... the site us pretty minimal as it is, so the benefit is marginal.

That said, I'm not fundamentally opposed to it, but I don't think it's something we need a nav button for, nor that we would want to do through javascript.  Instead, the [prefers-color-scheme media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) would allow for a CSS-only change that is automatically applied for people who have configured their browser or OS to indicate a dark mode preference.

I would also need to look into whether Twitter has a standard way of doing dark mode with the Feather CSS framework we use.  I did a quick internal search and I don't think there is, but I'd want to investigate a little more before committing to any particular implementation.

Also cc'ing @4kashyadav who had also indicated an intent to work on this.

2021-08-25 16:33 UTC, Chirag77302 commented
Thankyou @willnorris for your review , the changes were made in response to issue (#108 ) , wherein I felt that adding a standard and decent dark - light feature functionality would provide as a simple and decent additional feature to the website , and may also lead to further developments for the same in future by the community , similar to the one in the standard twitter website .

2021-08-25 16:41 UTC, willnorris commented
Yeah, the fact that the main Twitter app supports dark mode is one big thing that convinces me that it's fine to add here.  But since we don't already have any "settings" for the site, and the fact that the current implementation doesn't persist the preference, I think the prefers-color-scheme approach is probably the best, at least for the initial implementation.  Then it can kind of serve as a hidden easter egg for folks that have that enabled in their browser.  

What do you think?  Would you be up for switching this PR to use prefers-color-scheme?

2021-08-25 16:45 UTC, Chirag77302 commented
Yeah , thankyou @willnorris , I am up for this task .

2021-08-25 16:48 UTC, Chirag77302 commented
I totally agree with you @willnorris , still I think we can merge the given changes just for additional developments to the site , in the meantime I will add the necessary 'prefer-color-scheme' changes to it .

2021-08-25 18:17 UTC, willnorris commented
> still I think we can merge the given changes just for additional developments to the site

apologies if that wasn't clear, but that's what I was trying to get at earlier... I don't actually want to merge these changes as they currently exist.  If we're going to support dark mode, then we should use prefers-color-scheme to do it.

2021-08-25 19:12 UTC, Chirag77302 commented
Alright , @willnorris I will be working on the  'prefer-color-scheme' issue then , thankyou !

2021-08-26 18:31 UTC, Chirag77302 commented
@willnorris the changes have been made as asked yesterday using (prefer-color-scheme media feature) for the issue (#108 ) , kindly please review the changes .

2021-08-27 18:03 UTC, willnorris requested changes
This is great... definitely moving in the right direction!  We'll still need to work on the actual implementation a bit, and I've left comments throughout.

2021-08-27 18:03 UTC, willnorris commented on assets/css/_feather-component-button.scss
> +  background-color: white;
all of the `assets/css/_feather-*` files come directly from the internal feather framework we use at Twitter.  We shouldn't edit any of these files, since all of these changes would be overwritten the next time we update feather.  So this change will need to work with the existing feather styles, and then just override them for dark mode where appropriate.

I recognize that may make some of the dark mode CSS more verbose, since it may require duplicating a lot of selectors.  I can look into whether the feather team is willing to refactor things a bit to make it easier to do this kind of dark mode overriding, but in the meantime we will need to work with what we've got.

2021-08-27 18:03 UTC, willnorris commented on assets/css/_main.scss
> +@media (prefer-color-scheme: light){
In general, I don't think we should need any statements with `prefer-color-scheme: light`.  Instead, whatever the light-mode styling is should be the default (which is what we already have today), and then we just have a `prefer-color-scheme: dark` that overrides that.

For example, this light mode statement just duplicates what we already have up on line 61, so isn't actually needed at all.  Additionally, with SCSS, you can add the dark mode directly inline with the selector that you are overriding.  So for example, the `nav` block at line 60 could read:

``` css
nav {
  background-color: var(--tw-color-blue-primary);
  @media (prefers-color-scheme: dark) {
      background-color: black;
  }
}
```

2021-08-27 18:03 UTC, willnorris commented on assets/css/_main.scss
> +  .toggle-project {background-color: white;color: black;}
could you remove all of the code associated with the toggle button and the javascript approach to switching styles?  We're not going to want to check that in, and it makes the rest of the PR more difficult to review.

Of course, feel free to save those in a separate branch on your machine if you want to keep them for reference!  I just mean remove them from this PR.

2021-08-27 18:03 UTC, willnorris commented on assets/css/_main.scss
> +// @media (prefer-color-scheme: light){
if these commented out styles aren't needed (maybe you were testing some things?), go ahead and remove them.  Same thing throughout all the files... remove anything that isn't actually needed.

2021-08-27 20:06 UTC, Chirag77302 commented
Thankyou @willnorris for the suggestions , and apologies also , I 've cleaned up the code now ; all the changes that were asked have been made .

Talking of the javascript code , I don't think it is possible to do it with CSS as the embedded twitter theme toggling requires to set the   _**'data-theme'**_   attribute    **_(built in attributes for embedded twitter components)_** for the 2 anchor tags value every time the page loads , which unfortunately doesn't have a built in CSS function as far as my knowledge is concerned . 
And also setting the background color , text color values for these would be very complex .

Please do guide me if you know of any other alternative way of doing the same .
Rest all the changes asked have been made , please review them .

2021-08-27 21:18 UTC, willnorris requested changes
> Talking of the javascript code , I don't think it is possible to do it with CSS as the embedded twitter theme toggling requires to set the 'data-theme' attribute (built in attributes for embedded twitter components) for the 2 anchor tags value every time the page loads , which unfortunately doesn't have a built in CSS function as far as my knowledge is concerned .

Oh, I see what you're saying now... you're absolutely right.  I would have expected the embedded widgets to respect `prefers-color-scheme`.  I'll have to file an issue with the team to see if we can get that added.

In the meantime, since we only need to do anything if dark mode is set, ​the JS can be simplified to:

``` javascript
// set dark theme on twitter timeline widgets
if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
  for (const e of document.getElementsByClassName('twitter-timeline')) {
    e.setAttribute('data-theme','dark');
​  }
}
```

Also, that shouldn't be in `partials/ga.html`, since that file is specifically for google analytics.  I think just adding this to the bottom of `static/js/main.js` would be better.

With that, I think all of the other changes in `layouts/*` and probably `content/*` can be reverted, since they mostly seem to do with the toggle button.  There's also some lingering CSS relating to the toggle button that should be removed.

2021-08-27 21:18 UTC, willnorris commented on assets/css/_feather-component-button.scss
> +
you'll still need to move these changes out of the `_feather-component-button.scss` file.  Typically, when you see that a file is generated, like the `/* @generated */` comment at the top of this file, that's a pretty good indication you shouldn't modify it directly.  We could just move the dark mode overrrides for these button classes into `_main.scss`.

2021-08-28 07:13 UTC, Chirag77302 commented
All the necessary changes have been made @willnorris , talking of the javascript code , it doesn't seem to work in the `/static/js/main.js` file or the `/static/js/index.js` file , therefore I just cleaned up the code for the same function as you wanted it to be , and added the function to the` footer.html` file , just so that it does not get fumbled up with the google analytics .

Also the classes regarding toggle-button were removed earlier only , only the necessary ones which were needed to maintain the **`colour scheme pattern`** for the  **'_OS PAGE OF THE WEBSITE_'** have been kept . Rest all have been cleaned up .

2021-08-28 07:18 UTC, Chirag77302 commented on assets/css/_feather-component-button.scss
> +
This part of code was added in the original file itself , before any commits were made by me , therefore I preferred to leave it as it was .

2021-08-28 20:35 UTC, willnorris reviewed
> talking of the javascript code , it doesn't seem to work in the /static/js/main.js file or the /static/js/index.js file

It definitely does work in both main.js or index.js (though index.js is probably better, since this is only needed on the homepage).  You might need to restart Hugo or force refresh in your browser?

> Also the classes regarding toggle-button were removed earlier only , only the necessary ones which were needed to maintain the colour scheme pattern for the 'OS PAGE OF THE WEBSITE' have been kept . Rest all have been cleaned up .

I'm not really sure what you mean by this.  There are still a lot of inline styles and transitions directly in the html files, as well as some spurious whitespace changes.  You shouldn't need to edit any of the html files.

I took a pass at these changes to verify what I was saying was true.  If you want to take a peek, you can [see the changes here](https://github.com/willnorris/opensource-website/commit/70be8a8ef55ca8493eeddbbfe5b75781e18c9088) (ignore the Button styles... I'm still not sure of the best way to handle that.)

2021-08-28 20:35 UTC, willnorris commented on assets/css/_feather-component-button.scss
> +
I'm not sure what you mean by this.  Your PR here has changes to the `_feather-component-button.scss` file.

Unfortunately, because of the way some of the feather classes are structured, there are quite few that will need to be overrided to support dark mode for all the different button variants.  I'd recommend just ignoring button styling for now, and I'll try to figure out a solution there.

2021-08-28 20:35 UTC, willnorris commented on assets/css/projects.scss
> +	color: black;
as noted elsewhere, don't change the default styling.  Only add overrides for dark mode

2021-08-28 20:35 UTC, willnorris commented on assets/css/_main.scss
> +.explore-projects{
you shouldn't need to define any additional styling for the default (light) theme.  The only CSS additions should be dark mode overrides in the right locations.

For example, for what you're trying to do here (as well as with .section and .all-projects below) is better done simply by overriding the background and color on the body class up around line 45:

``` css
body {
  background-color: white;

  @media (prefers-color-scheme: dark) {
    background-color: var(--tw-color-gray-900-experimental);
    color: var(--tw-color-gray-faint);
  }
}
```

2021-08-28 20:35 UTC, willnorris commented on assets/css/projects.scss
> +a:link, .project-links a:visited {
this shouldn't be changed.

2021-08-28 21:48 UTC, closed without merging

2021-08-28 21:50 UTC, willnorris commented
for simplicity, I went head and reduced your changes down to the core CSS changes and merged them as 76981e0da5d65c6ca04ce6fe74d97473b189942d.  I then did a little bit more refactoring and took a first stab at customizing the buttons.  This should give us a good foundation now to continue to iterate on tweaking dark mode.  Thanks for your work and patience on this!

2021-08-29 05:08 UTC, Chirag77302 commented
> for simplicity, I went head and reduced your changes down to the core CSS changes and merged them as [76981e0](https://github.com/twitter/opensource-website/commit/76981e0da5d65c6ca04ce6fe74d97473b189942d). I then did a little bit more refactoring and took a first stab at customizing the buttons. This should give us a good foundation now to continue to iterate on tweaking dark mode. Thanks for your work and patience on this!

@willnorris kindly can you please make a confirmation whether the changes have been merged by adding the **'MERGED'** tag to this PR .

2021-08-29 05:42 UTC, willnorris commented
yes, they have been merged in commit 76981e0da5d65c6ca04ce6fe74d97473b189942d.  It's the same code you provided in this PR and lists you as the author, I just squashed the commits into a single one, and removed some of the unrelated bits.

Unfortunately, because I had to make local edits to the commit like that, GitHub lists this PR as "closed" rather than "merged", and there's no way to change this.  It's a little annoying, but rest assured your changes were actually merged.

2021-08-29 06:01 UTC, Chirag77302 commented
> yes, they have been merged in commit [76981e0](https://github.com/twitter/opensource-website/commit/76981e0da5d65c6ca04ce6fe74d97473b189942d). It's the same code you provided in this PR and lists you as the author, I just squashed the commits into a single one, and removed some of the unrelated bits.
> 
> Unfortunately, because I had to make local edits to the commit like that, GitHub lists this PR as "closed" rather than "merged", and there's no way to change this. It's a little annoying, but rest assured your changes were actually merged.

Thankyou @willnorris , it was really nice working with you , please feel free to put up any new issues on any of the repositories , I will be happy to contribute . 
P.S - Apologies as I didn't realize the fact that you didn't want me to override the set CSS features for the light mode , I just felt that it my changes improved the UI to some extent . 😅😅 Have a nice day !

2021-08-29 06:07 UTC, willnorris commented
Ah, interesting... I didn't realize you were intentionally trying to improve the light mode UI as well.  My apologies!

I probably still would have asked you to move that to a separate PR so that I could review that independent of the dark mode changes.  And if you do still have some ideas on improving the UI, by all means, feel free to open a new PR with those changes, as I'd be happy to take a look.

2021-08-29 06:35 UTC, Chirag77302 commented
> Ah, interesting... I didn't realize you were intentionally trying to improve the light mode UI as well. My apologies!
> 
> I probably still would have asked you to move that to a separate PR so that I could review that independent of the dark mode changes. And if you do still have some ideas on improving the UI, by all means, feel free to open a new PR with those changes, as I'd be happy to take a look.

Sure thing , looking forward to it .